### ISSUE TITLE
wtyczka nie działa Python error

### ISSUE THREAD

**Issue by pawelstaporek** [envirosolutionspl/pobieracz_danych_gugik#11]
Przy próbie uruchomienia plugina wyskakuje mi błąd Python:

> 2021-12-12T23:08:09     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
              httplib_response = self._make_request(
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
              self._validate_conn(conn)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
              conn.connect()
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connection.py", line 362, in connect
              self.sock = ssl_wrap_socket(
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
              return context.wrap_socket(sock, server_hostname=server_hostname)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\ssl.py", line 500, in wrap_socket
              return self.sslsocket_class._create(
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\ssl.py", line 1040, in _create
              self.do_handshake()
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\ssl.py", line 1309, in do_handshake
              self._sslobj.do_handshake()
             ssl.SSLError: A failure in the SSL library occurred (_ssl.c:1129)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\adapters.py", line 439, in send
              resp = conn.urlopen(
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
              retries = retries.increment(
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\urllib3\util\retry.py", line 446, in increment
              raise MaxRetryError(_pool, url, error or ResponseError(cause))
             urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by SSLError(SSLError(1, 'A failure in the SSL library occurred (_ssl.c:1129)')))
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/PASTO/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 161, in run
              self.dockwidget = PobieraczDanychDockWidget()
              File "C:\Users/PAST/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\dialogs.py", line 57, in __init__
              self.regionFetch = RegionFetch()
              File "C:\Users/PAST/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\uldk.py", line 4, in __init__
              self.wojewodztwoDict = self.__fetchWojewodztwoDict()
              File "C:\Users/PAST/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\uldk.py", line 22, in __fetchWojewodztwoDict
              resp = requests.get('https://uldk.gugik.gov.pl/service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt')
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\api.py", line 76, in get
              return request('get', url, params=params, **kwargs)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\api.py", line 61, in request
              return session.request(method=method, url=url, **kwargs)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\sessions.py", line 530, in request
              resp = self.send(prep, **send_kwargs)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\sessions.py", line 643, in send
              r = adapter.send(request, **kwargs)
              File "C:\PROGRA~1\QGIS32~1.1\apps\Python39\lib\site-packages\requests\adapters.py", line 514, in send
              raise SSLError(e, request=request)
             requests.exceptions.SSLError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by SSLError(SSLError(1, 'A failure in the SSL library occurred (_ssl.c:1129)')))

**Comment by envirosolutionspl** [comment]
Wygląda jak problem po stronie serwera. Odrzuca połączenie. Czy problem nadal występuje?
