### ISSUE TITLE
Błąd przy pobieraniu NMT

### ISSUE THREAD

**Issue by wkaczan** [envirosolutionspl/pobieracz_danych_gugik#122]
W ostatnim czasie przy próbie pobrania danych NMT zarówno przy wykorzystaniu warstwy wektorowej jak i punktu otrzymuję błąd:

`TypeError: __init__() got an unexpected keyword argument 'dt_pzgik' 
Traceback (most recent call last):
  File "C:\Users/wojciech.kaczan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 695, in canvasNmt_clicked
    self.downloadNmtForSinglePoint(point)
  File "C:\Users/wojciech.kaczan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 647, in downloadNmtForSinglePoint
    isEvrf2007=isEvrf2007) if isNmpt else nmt_api.getNmtListbyPoint1992(
  File "C:\Users/wojciech.kaczan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\nmt_api.py", line 62, in getNmtListbyPoint1992
    lista += createList(resp)
  File "C:\Users/wojciech.kaczan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\nmt_api.py", line 83, in createList
    nmt = Nmt(**params)
TypeError: __init__() got an unexpected keyword argument 'dt_pzgik'
`

Ustawienia:
![obraz](https://github.com/envirosolutionspl/pobieracz_danych_gugik/assets/51786569/25148be9-96e2-4e2d-bb2f-522dc197bbcd)

**Comment by wojtek19022** [comment]
@wkaczan pozwolisz, że zamknę wątek. Został on rozwiązany w Issue #105 i przy pracach pod koniec tygodnia lub od 27.04 będzie dostępna nowa wersja wtyczki.
