### ISSUE TITLE
Błąd przy pobieraniu 

### ISSUE THREAD

**Issue by ekolabynet** [envirosolutionspl/pobieracz_danych_gugik#124]
Dzień dobry, 
używam wtyczki Pobieracz na QGIS 3 Kubuntu 24.4. Od pewnego czasu przy pobieraniu którychkolwiek materiałów z usługi WMS/Geoportal zgłasza mi błąd. 
Czy to kwestia mojej instalacji,czy też jest to jakiś problem z PZGIK?
Pozdrawiam
PM

******
ORTOFOTOMAPA
2024-05-25T08:55:43     WARNING    Traceback (most recent call last):
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 554, in canvasOrto_clicked
              self.downloadOrtoForSinglePoint(point)
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 513, in downloadOrtoForSinglePoint
              ortoList = ortofoto_api.getOrtoListbyPoint1992(point=point1992)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/ortofoto_api.py", line 48, in getOrtoListbyPoint1992
              ortofotomapa = Ortofotomapa(**params)
              ^^^^^^^^^^^^^^^^^^^^^^
             TypeError: Ortofotomapa.__init__() got an unexpected keyword argument 'dt_pzgik'

******
NMT
2024-05-25T09:00:02     WARNING    Traceback (most recent call last):
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 695, in canvasNmt_clicked
              self.downloadNmtForSinglePoint(point)
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 647, in downloadNmtForSinglePoint
              isEvrf2007=isEvrf2007) if isNmpt else nmt_api.getNmtListbyPoint1992(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 62, in getNmtListbyPoint1992
              lista += createList(resp)
              ^^^^^^^^^^^^^^^^
              File "/home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/nmt_api.py", line 83, in createList
              nmt = Nmt(**params)
              ^^^^^^^^^^^^^
             TypeError: Nmt.__init__() got an unexpected keyword argument 'dt_pzgik'
             
******

**Comment by ekolabynet** [comment]
Wersja QGIS  | 3.36.3-Maidenhead
Wersja wtyczki | Zainstalowana wersja	[1.0.10] (file:///home/piotr/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik)

**Comment by wojtek19022** [comment]
Dzień dobry, wypuściliśmy ostatnio aktualizację i zostało to naprawione :) Był to problem po stronie GUGIK
