### ISSUE TITLE
Błąd Pythona : Wystąpił błąd podczas wykonywania kodu Pythona

### ISSUE THREAD

**Issue by lukas12p** [envirosolutionspl/pobieracz_danych_gugik#126]
Przy próbie pobrania LAZ warstwą wektorową
Wtyczka 1.1.0

Traceback (most recent call last):
              File "C:\Users/xxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 781, in las_fromLayer_btn_clicked
              sub_list = las_api.getLasListbyPoint1992(point, self.dockwidget.las_evrf2007_rdbtn.isChecked())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/xxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\las_api.py", line 56, in getLasListbyPoint1992
              las = Las(**params)
              ^^^^^^^^^^^^^
             TypeError: Las.__init__() got an unexpected keyword argument 'bladSredniPolozenia'

**Comment by wojtek19022** [comment]
Dzień dobry, błąd wynika ze zmiany struktury danych pozyskiwanych z GUGIK'u. Błąd zostanie naprawiony w wersji 1.1.1 :)
