### ISSUE TITLE
Błąd przy pobieraniu plików LAZ

### ISSUE THREAD

**Issue by aswiader** [envirosolutionspl/pobieracz_danych_gugik#13]
Próba pobrania plików LAZ przez wskazanie punktu na mapie powoduje błąd Pythona (poniżej), a pobieranie za pomocą warstwy wektorowej wyświetla komunikat "Nie znaleziono danych spełniających kryteria". Testowane dla lokalizacji w Krakowie, gdzie kilka tygodni temu pobrałem bez problemu pliki LAZ.

2022-02-09T08:06:47     WARNING    Traceback (most recent call last):
              File "C:\Users/Andrzej/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 678, in canvasLas_clicked
              self.downloadLasForSinglePoint(point)
              File "C:\Users/Andrzej/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 639, in downloadLasForSinglePoint
              self.filterLasListAndRunTask(lasList)
              File "C:\Users/Andrzej/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 646, in filterLasListAndRunTask
              lasList = list(set(lasList))
             TypeError: 'NoneType' object is not iterable

**Comment by envirosolutionspl** [comment]
wygląda na to, że GUGiK Wyłączył dostęp bez logowania do usługi WFS z listą warstw LAZ

**Comment by aswiader** [comment]
Chyba nie, z geoportalu można pobierać normalnie. Ale zdaje się, że coś pozmieniali:
https://www.geoportal.gov.pl/o-geoportalu/aktualnosci/-/asset_publisher/HCHq0YGNRszn/content/09-02-2022-nowe-uslugi-wms-umozliwiajace-pobieranie-danych-wysokosciowych?redirect=%2F&inheritRedirect=true

**Comment by envirosolutionspl** [comment]
poprawione w wersji 0.9.1

**Comment by aswiader** [comment]
Świetna robota - dziękuję! Wasza wtyczka jest bardzo przydatna.
