### ISSUE TITLE
Błąd pythona NMT

### ISSUE THREAD

**Issue by Martamys** [envirosolutionspl/pobieracz_danych_gugik#18]
Od wczoraj (08/06/2022) występuje błąd pythona przy pobieraniu danych NMT z geoportalu, reszta danych pobierana jest bez problemu. Moja wersja wtyczki to 0.9.2.
Błąd:
Traceback (most recent call last):
              File "QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 545, in canvasNmt_clicked
              self.downloadNmtForSinglePoint(point)
              File "QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\pobieracz_danych_gugik.py", line 499, in downloadNmtForSinglePoint
              isEvrf2007=isEvrf2007) if isNmpt else nmt_api.getNmtListbyPoint1992(
              File "QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\nmt_api.py", line 60, in getNmtListbyPoint1992
              return True, createList(resp)
              File "QGIS/QGIS3\profiles\default/python/plugins\pobieracz_danych_gugik\nmt_api.py", line 78, in createList
              nmt = Nmt(**params)
             TypeError: __init__() got an unexpected keyword argument 'zrDanych'

**Comment by lukasz-komorowski** [comment]
Czy można spodziewać się naprawy tego błędu? Jeżeli tak to kiedy mniej więcej?

**Comment by envirosolutionspl** [comment]
Błąd poprawiony w wersji 0.9.3
