### ISSUE TITLE
TypeError: 'NoneType' w QGIS 3.26/Ubuntu 22.04

### ISSUE THREAD

**Issue by merkato** [envirosolutionspl/pobieracz_danych_gugik#48]
Przy próbie wskazania punktu na mapie dla pobrania danych, QGIS wyrzuca błąd pythona. Świeża instalacja Ubuntu, oraz QGIS z stabilnego repo

TypeError: 'NoneType' object is not iterable 
Traceback (most recent call last):
  File "/home/tomasz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 547, in canvasOrto_clicked
    self.downloadOrtoForSinglePoint(point)
  File "/home/tomasz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 506, in downloadOrtoForSinglePoint
    self.filterOrtoListAndRunTask(ortoList)
  File "/home/tomasz/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 513, in filterOrtoListAndRunTask
    ortoList = list(set(ortoList))
TypeError: 'NoneType' object is not iterable

Wersja Pythona: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] 
Wersja QGIS: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdad

**Comment by envirosolutionspl** [comment]
znowu musiały być jakieś zmiany po stronie API, do poprawy
