### ISSUE TITLE
Wystąpił błąd podczas wykonywania kodu Pythona:   requests.exceptions.SSLError: HTTPSConnection...

### ISSUE THREAD

**Issue by bpieklo** [envirosolutionspl/pobieracz_danych_gugik#49]
Witam, 

Mój system to Manjaro Linux, qgis jest w wersji 3.28.3 wtyczka ver.1.02.

Przy uruchamianiu wtyczki wyskakuje mi następujący błąd:

`requests.exceptions.SSLError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)'))) 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pieklo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/pobieracz_danych_gugik.py", line 172, in run
    self.dockwidget = PobieraczDanychDockWidget()
  File "/home/pieklo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/dialogs.py", line 57, in __init__
    self.regionFetch = RegionFetch()
  File "/home/pieklo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/uldk.py", line 4, in __init__
    self.wojewodztwoDict = self.__fetchWojewodztwoDict()
  File "/home/pieklo/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pobieracz_danych_gugik/uldk.py", line 37, in __fetchWojewodztwoDict
    resp = requests.get('https://uldk.gugik.gov.pl/service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt')
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='uldk.gugik.gov.pl', port=443): Max retries exceeded with url: /service.php?obiekt=wojewodztwo&wynik=wojewodztwo,teryt (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))`

Zastanawiam się jak to naprawić i czy wina leży po stronie serwera, czy jednak coś nie tak z biblioteką requests u mnie?

**Comment by envirosolutionspl** [comment]
Nastąpiły zmiany po stronie serwera z którymi QGIS sobie nie radził. W wersji 1.0.3 już powinno działać https://github.com/envirosolutionspl/pobieracz_danych_gugik/releases/tag/v1.0.3

**Comment by Ueschar** [comment]
Zostało sprawdzone i teraz, na nowszych wersjach wtyczki, ten błąd nie występuję

**Comment by wojtek19022** [comment]
@Ueschar na jakiej wersji QGIS na linuxie sprawdzałeś?

**Comment by Ueschar** [comment]
> @Ueschar na jakiej wersji QGIS na linuxie sprawdzałeś?
na 3.34 i 3.36

**Comment by wojtek19022** [comment]
To tylko dodaj proszę komunikat w przypadku takiego błędu, zeby wyświetlił się użytkownikowi zamiast komunikatu pythona i uodpornij wtyczkę, żeby wtedy np. nie zatrzymała się lub nie przestała działać
